In [11]:
import numpy as np
import jax.numpy as jnp
from jax import vmap

In [12]:
def mm(x, y):
    return jnp.matmul(x, y)

bmm = vmap(mm)

In [14]:
X = [[1, 2, 3],
     [4, 5, 6]]
Y = [[0, 1],
     [1, 0],
     [1, 1]]

X = np.array(X)
Y = np.array(Y)

np.matmul(X, Y)

array([[ 5,  4],
       [11, 10]])

In [21]:
jX = jnp.array(X)
jY = jnp.array(Y)

jnp.matmul(jX, jY)

error: 'func.return' op created with unregistered dialect. If this is intended, please call allowUnregisteredDialects() on the MLIRContext, or use -allow-unregistered-dialect with the MLIR opt tool used
error: 'func.return' op created with unregistered dialect. If this is intended, please call allowUnregisteredDialects() on the MLIRContext, or use -allow-unregistered-dialect with the MLIR opt tool used


RuntimeError: UNKNOWN: -:7:18: error: operation being parsed with an unregistered dialect. If this is intended, please use -allow-unregistered-dialect with the MLIR tool used


[[1 2 3]
 [4 5 6]]
